ramanbhandari/vamoose

Documentation/CONTRIBUTING.md, README.md
Created CONTRIBUTING.md to establish criteria for creating pull request, commits and branches to avoid conflicts and be consistent.
=> Create CONTRIBUTING to establish guidelines for development

.github/workflows/discord-pr-notifications.yml, Documentation/CONTRIBUTING.md
Creates Github action to send update to the team discord server for all PR updates. 
Also added a documentation update for workflow branch name.
=> Workflow - Discord notification for PR updates

server/.gitignore, server/.prettierignore, server/.prettierrc, server/eslint.config.mjs, server/package-lock.json, server/package.json, server/src/controllers/planController.ts, server/src/routes/plans.ts, server/src/server.ts, server/tsconfig.json
Added file structure for the server. Setup TypeScript, ESLint and Prettier.
=> setting up nodejs with typescript. 

Documentation/CONTRIBUTING.md
Fixed the branch naming convention
=> Update CONTRIBUTING.md according to feedback

frontend/app/ThemeProvider.tsx, frontend/app/dashboard/page.tsx, frontend/app/globals.css, frontend/app/layout.tsx, frontend/app/login/AuthForm.tsx, frontend/components/ThemeToggle.tsx, frontend/components/footer/Footer.tsx, frontend/components/navbar/Navbar.tsx, frontend/theme/theme.ts
Created logout button on nav
Navbar doesn't show Vamoose on login page
Footer is stick for login page
Issue: 107
=> #107 - Created footer navbar with logout and dark/light mode tooltip

frontend/app/globals.css, frontend/app/trips/[:tripId]/page.tsx, frontend/app/trips/[:tripId]/sections/Activities.tsx, frontend/app/trips/[:tripId]/sections/Dates.tsx, frontend/app/trips/[:tripId]/sections/Destinations.tsx, frontend/app/trips/[:tripId]/sections/Expenses.tsx, frontend/app/trips/[:tripId]/sections/Itinerary.tsx, frontend/app/trips/[:tripId]/sections/Overview.tsx, frontend/app/trips/[:tripId]/sections/PackingList.tsx, frontend/app/trips/[:tripId]/sections/Polls.tsx, frontend/app/trips/[:tripId]/sections/Stays.tsx, frontend/app/trips/[:tripId]/sections/TripMembers.tsx, frontend/components/blocks/Components/Dock/Dock.tsx, frontend/components/navbar/Navbar.tsx, frontend/package-lock.json, frontend/package.json, frontend/theme/theme.ts
Non-functional Trip Summary page.
Has a dock for all components of trip.
Uses reactbits modified Dock component
=> 33 UI for trip summary page

frontend/app/layout.tsx, frontend/app/trips/[tripId]/page.tsx, frontend/app/trips/[tripId]/sections/Expenses.tsx, frontend/app/trips/[tripId]/sections/Overview.tsx, frontend/components/NotificationSnackbar.tsx, frontend/components/trips/Overview/BudgetDonut.tsx, frontend/package-lock.json, frontend/package.json, frontend/stores/notification-store.ts, frontend/stores/trip-store.ts
Expense Page UI with ability to add Expense.
Initialized Global State management store for Trip Data and Notifications.
Integrated Notification component in layout to not require including in every page.
Note: Delete Expense is going to be part of other issues. This is only add and list.
Issue: #44 #45
=> 44-45-Create Expense UI to add expense and filters

frontend/app/dashboard/Skeleton.tsx, frontend/app/dashboard/page.tsx
Add Current trips section.
Don't preload dashboard header images if its not a page re-mount (eg if it is back navigation from other route)
Move Skeleton to a new file
=> 176 - Adds current trip section to dashboard.

frontend/app/trips/[tripId]/sections/Expenses.tsx, frontend/app/trips/create/page.tsx, frontend/components/NotificationSnackbar.tsx, frontend/components/trips/Overview/BudgetDonut.tsx, frontend/stores/notification-store.ts, frontend/stores/trip-store.ts
Enables Single or Multiple Expense Delete. Updates State for Budget Ring as well.
=>  178 - Implements delete single or multiple expenses

frontend/Dockerfile, frontend/README.md, frontend/next.config.js, frontend/package-lock.json, frontend/package.json, frontend/tsconfig.json, server/Dockerfile, server/prisma/schema.prisma
Dockerfile in root server and frontend folder
Had to do some changes for it to work - changing next.config.ts to .js
Added binary target to Prisma schema as well so it needs to be re generated now
Updated readme in frontend root
=> Dockerize the app

frontend/Dockerfile, frontend/README.md, frontend/next.config.js, frontend/package-lock.json, frontend/package.json, frontend/tsconfig.json, server/Dockerfile, server/prisma/schema.prisma
Create dockerfile in root frontend and server dir. Update Readme in frontend with instructions. (#181)
=> Merge: Dev to UAT

.github/workflows/ci-frontend.yml, .github/workflows/ci-server.yml, .github/workflows/push_dockerhub.yml, docker-compose.yml, frontend/Dockerfile, frontend/README.md, server/README.md, server/src/routes/expenseShare.routes.ts
Updated CI workflow to trigger on every push and to run the checks in Docker.
Added a new workflow to push two images to DockerHub on every push to main and also allow a manual trigger for testing this issue lolls that it works!!
Created a root Docker compose file to start both containers together locally.
=> 214 - CI/CD updates/enhancements

frontend/app/trips/[tripId]/sections/Overview/TripHeader.tsx, frontend/app/trips/create/page.tsx
Affects - Overview edit and Create Trip
=> End date picker should start from startdate + 1 day

frontend/app/dashboard/page.tsx, frontend/app/trips/[tripId]/sections/Expenses/AllExpenses.tsx, frontend/app/trips/[tripId]/sections/Expenses/ExpenseBreakdown.tsx, frontend/app/trips/[tripId]/sections/Expenses/MemberOwedCard.tsx, frontend/app/trips/[tripId]/sections/Overview/TravelSquad.tsx, frontend/app/trips/[tripId]/sections/Polls/CreatePollDialog.tsx, frontend/app/trips/[tripId]/sections/Polls/PollItem.tsx, frontend/app/trips/[tripId]/sections/TripMembers/MemberCard.tsx, frontend/app/trips/[tripId]/sections/TripMembers/index.tsx, frontend/components/TripCard.tsx, frontend/stores/trip-store.ts, frontend/types/index.ts, server/src/models/trip.model.ts
Mostly UI improvements. Polls text change from complete to end poll. Included Name initials in avatar instead of C or M in Members page and members section in overview Page. Hover in Overview members section now shows full name instead of email. Added Full name to members card in Members page as well and moved the email to be smaller. Changed colors of the role chip in members card. And some other improvements please let me know if any questions!
Note: you may need to create new account to see full name, old account will see emails only and C and M in avatar since the script is running for new accounts thanks to Chuks merging it this morning.
=> Bug fixes minor improvements

frontend/components/chat/Chat.tsx, frontend/package-lock.json, frontend/package.json
First draft of final chat UI
Please tell me if you need changes! 🤪
=> 268 add the option to send emojis and reactions in chat

frontend/app/trips/[tripId]/sections/Itinerary/EventModal.tsx, frontend/app/trips/[tripId]/sections/Itinerary/LocationAutocomplete.tsx, frontend/app/trips/[tripId]/sections/Itinerary/index.tsx, frontend/app/trips/[tripId]/sections/Itinerary/types.ts
UI only, won't create an event. Just logs in console for now. Integrated the autocomplete for Location.
=> 85 form for creating an event

frontend/components/trips/Overview/BudgetDonut.tsx
Affects the ring in Overview and Expenses sections
=> 261 - Warn user in budget ring if near or over budget

frontend/app/globals.css, frontend/app/trips/[tripId]/sections/Expenses/AllExpenses.tsx, frontend/app/trips/[tripId]/sections/Expenses/MemberOwedCard.tsx, frontend/app/trips/[tripId]/sections/Itinerary/CalendarView/CalendarView.tsx, frontend/app/trips/[tripId]/sections/Itinerary/EventModal.tsx, frontend/app/trips/[tripId]/sections/Itinerary/ListView/DeleteConfirmationDialog.tsx, frontend/app/trips/[tripId]/sections/Itinerary/ListView/EventCard.tsx, frontend/app/trips/[tripId]/sections/Itinerary/ListView/ListView.tsx, frontend/app/trips/[tripId]/sections/Itinerary/index.tsx
State management on Edit/Delete in Calendar View
Add delete confirmation dialog for deleting event
Show scroll hint in create event modal so user knows they can scroll to see hidden fields in the bottom
Some code refactor/cleanup
Also a couple fixes in Expenses section
=> 367 itinerary UI bug fixes and enhancements

frontend/components/chat/Chat.tsx, frontend/stores/message-store.ts, frontend/stores/user-store.ts, frontend/utils/socketClient.ts
Should hopefully be fixing the prod chat bug.
Also fixes the message overflowing on the bubble. The bubble is now capped to 75%.
=> 356 chat prod bugs

frontend/components/chat/Chat.tsx, frontend/stores/message-store.ts, frontend/stores/user-store.ts, frontend/utils/socketClient.ts
* fixed socket initialization and disconnect logic
* fix overflowing text from bubble, max 75 percent
=> Dev to UAT

frontend/components/chat/Chat.tsx, frontend/stores/message-store.ts, frontend/stores/user-store.ts, frontend/utils/socketClient.ts
* fixed socket initialization and disconnect logic
* fix overflowing text from bubble, max 75 percent
=> Uat to MAIN - 356 chat prod bugs (#372)

frontend/app/trips/[tripId]/sections/Itinerary/CalendarView/CalendarView.tsx, frontend/app/trips/[tripId]/sections/Itinerary/ListView/EventCard.tsx, frontend/app/trips/[tripId]/sections/Itinerary/ListView/ListView.tsx, frontend/app/trips/[tripId]/sections/Itinerary/index.tsx
Admin/Creator of the trip and Creator of Event - Edit/Delete the event
Admin/Creator of the trip and Creator of Event - Assign/Un-assign members
Creator of event - Can update/delete the note
=> Added role permissions in itinerary events

frontend/app/trips/[tripId]/sections/Polls/CreatePollDialog.tsx
Included timezone in the expiresAt date string
=> send timezone with expiry date
